stages:
- name: Build
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: python pytest.py
  - publishImageConfig:
      dockerfilePath: ./nginx/Dockerfile
      buildContext: .
      tag: stijnp/basic-webapp
      registry: 127.0.0.1:34615
  - publishImageConfig:
      dockerfilePath: ./web/Dockerfile
      buildContext: .
      tag: stijnp/webapp-nginx
      registry: 127.0.0.1:34615
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./kubernetes/webapp-deployment.yaml
  - applyYamlConfig:
      path: ./kubernetes/nginx-deployment.yaml
  - applyYamlConfig:
      path: ./kubernetes/postgres-deployment.yaml
  - applyYamlConfig:
      path: ./kubernetes/nginx-service.yaml
  - applyYamlConfig:
      path: ./kubernetes/postgres-service.yaml
  - applyYamlConfig:
      path: ./kubernetes/webapp-service.yaml
timeout: 60
notification: {}
