stages:
- name: Build
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: python pytest.py
  - publishImageConfig:
      dockerfilePath: ./web/Dockerfile
      buildContext: ./web
      tag: stijnpietersnmct/project4-webapp
      pushRemote: true
      registry: index.docker.io
  - publishImageConfig:
      dockerfilePath: ./nginx/Dockerfile
      buildContext: ./nginx
      tag: stijnpietersnmct/project4-nginx
      pushRemote: true
      registry: index.docker.io
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./kubernetes/prod-webapp-deployment.yaml
  - applyYamlConfig:
      path: ./kubernetes/prod-nginx-deployment.yaml
  - applyYamlConfig:
      path: ./kubernetes/prod-postgres-deployment.yaml
  - applyYamlConfig:
      path: ./kubernetes/prod-nginx-service.yaml
  - applyYamlConfig:
      path: ./kubernetes/prod-postgres-service.yaml
  - applyYamlConfig:
      path: ./kubernetes/prod-webapp-service.yaml
timeout: 60
branch:
  include:
  - dev
  exclude:
  - master
notification: {}
