apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: development
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres
status:
  loadBalancer: {}
