apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: postgres
  namespace: development
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: postgres
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50