apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: webapp
  namespace: development
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50