apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp
  namespace: development
spec:
  selector:
    matchLabels:
      app: webapp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webapp
        gitcommit: ${CICD_GIT_COMMIT}
    spec:
      containers:
      - args:
        - uwsgi
        - --ini
        - app.ini
        env:
        - name: PG_DATABASE
          value: labo
        - name: PG_HOST
          value: postgres
        - name: PG_PASSWORD
          value: student_password
        - name: PG_PORT
          value: "5432"
        - name: PG_USER
          value: student_user
        image: stijnpietersnmct/project4-webapp
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
        name: webapp
        resources:
          requests:
            cpu: "400m"
            memory: "500Mi"
          limits:
            cpu: "800m"
            memory: "1Gi"
      restartPolicy: Always