apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: development
spec:
  selector:
    matchLabels:
     app: postgres
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        app: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: labo
        - name: POSTGRES_PASSWORD
          value: student_password
        - name: POSTGRES_USER
          value: student_user
        image: postgres:12.1-alpine
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-pv-claim
        name: postgres
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 15
            periodSeconds: 20
        resources:
          requests:
            cpu: "300m"
          limits:
            cpu: "600m"
      volumes:
        - name: postgres-pv-claim
          persistentVolumeClaim:
            claimName: postgres-pv-claim
      restartPolicy: Always
status: {}
