apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
  name: webapp
  namespace: production
spec:
  type: NodePort
  ports:
    - port: 5000
  selector:
    app: webapp
status:
  loadBalancer: {}
