apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - args:
        - uwsgi
        - --ini
        - app.ini
        env:
        - name: PG_DATABASE
          value: labo
        - name: PG_HOST
          value: postgres
        - name: PG_PASSWORD
          value: student_password
        - name: PG_PORT
          value: "5432"
        - name: PG_USER
          value: student_user
        image: eslih/basic-webapp:v1.0.9
        name: webapp
        resources: 
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "50m"
      restartPolicy: Always
